### ISSUE TITLE
Handle failed image lookup gracefully

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#172]
Some users want images to be optional on some items, and so leave their dynamic image name columns blank for those items. The new renderer seems to crash in that instance, whereas the old renderer would gracefully move on to the next layer.

Here's the stack trace a user reported that I used to diagnose this issue, double-check because I might not be correct!

```
image_renderer.js:164 Error: No image found with name: .png
    at https://beta.editor.paperize.io/assets/index.1f9c56da.js:420:25902
From previous event:
    at CA (https://beta.editor.paperize.io/assets/index.1f9c56da.js:420:25839)
    at Object.render (https://beta.editor.paperize.io/assets/index.1f9c56da.js:420:27425)
    at https://beta.editor.paperize.io/assets/index.1f9c56da.js:421:3223
From previous event:
    at https://beta.editor.paperize.io/assets/index.1f9c56da.js:421:3216
From previous event:
    at https://beta.editor.paperize.io/assets/index.1f9c56da.js:421:3053
From previous event:
    at v2 (https://beta.editor.paperize.io/assets/index.1f9c56da.js:421:3027)
    at Object.renderItemToPdf (https://beta.editor.paperize.io/assets/index.1f9c56da.js:421:4742)
    at async u.<anonymous> (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1224:11537)
(anonymous) @ image_renderer.js:164
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
image_provider.js:44 Uncaught (in promise) Error: No image found with name: .png
    at https://beta.editor.paperize.io/assets/index.1f9c56da.js:420:25902
From previous event:
    at CA (https://beta.editor.paperize.io/assets/index.1f9c56da.js:420:25839)
    at gY (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1224:4201)
    at aY (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1223:9650)
    at https://beta.editor.paperize.io/assets/index.1f9c56da.js:1223:9497
From previous event:
    at sY (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1223:9474)
    at Xp (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1223:7134)
    at rY (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1223:7373)
    at u.renderPDF (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1224:11411)
    at u.rerender (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1224:10839)
    at u.mounted (https://beta.editor.paperize.io/assets/index.1f9c56da.js:1224:8293)
    at Wa (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:21751)
    at zs (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:29370)
    at Object.insert (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:32804)
    at D (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:53379)
    at u.__patch__ (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:54751)
    at t._update (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:27045)
    at u.r (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:27790)
    at t.get (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:24017)
    at t.run (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:24754)
    at gO (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:29924)
    at Array.<anonymous> (https://beta.editor.paperize.io/assets/index.1f9c56da.js:5:22771)
(anonymous) @ image_provider.js:44
```

Reported by `@VergentAdmin` on Discord.

**Comment by shawn-mcgee** [comment]
Looking at this stack trace it looks like this error occurs within the original pdf renderer? The trace points to image_renderer.js which appears to be part of the original renderer?

**Comment by shawn-mcgee** [comment]
I've been able to test this and can confirm it is a problem with the new renderer. Working on a fix rn!
