### ISSUE TITLE
PNG renderer error

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#68]
**Describe the bug**
Throws an error when switching to the PNG renderer

**To Reproduce**
1. Click "edit" on a source.
2. Reselect your spreadsheet
3. Select the worksheet. Select quantity column.
4. Switch to png renderer preview, get this:

```
Cannot read property 'children' of undefined
TypeError: Cannot read property 'children' of undefined
    at https://beta.editor.paperize.io/editor.js:21:129418
    at u (https://beta.editor.paperize.io/editor.js:15:100304)
    at O._settlePromiseFromHandler (https://beta.editor.paperize.io/editor.js:15:73731)
    at O._settlePromise (https://beta.editor.paperize.io/editor.js:15:74531)
    at O._settlePromise0 (https://beta.editor.paperize.io/editor.js:15:75230)
    at O._settlePromises (https://beta.editor.paperize.io/editor.js:15:76557)
    at O._fulfill (https://beta.editor.paperize.io/editor.js:15:75600)
    at O._resolveCallback (https://beta.editor.paperize.io/editor.js:15:72475)
    at O._settlePromiseFromHandler (https://beta.editor.paperize.io/editor.js:15:73885)
    at O._settlePromise (https://beta.editor.paperize.io/editor.js:15:74531)
    at O._settlePromise0 (https://beta.editor.paperize.io/editor.js:15:75230)
    at O._settlePromises (https://beta.editor.paperize.io/editor.js:15:76557)
    at O._fulfill (https://beta.editor.paperize.io/editor.js:15:75600)
    at O._resolveCallback (https://beta.editor.paperize.io/editor.js:15:72475)
    at O._settlePromiseFromHandler (https://beta.editor.paperize.io/editor.js:15:73885)
    at O._settlePromise (https://beta.editor.paperize.io/editor.js:15:74531)
From previous event:
    at O.B [as _captureStackTrace] (https://beta.editor.paperize.io/editor.js:15:43615)
    at O._then (https://beta.editor.paperize.io/editor.js:15:69184)
    at O.then (https://beta.editor.paperize.io/editor.js:15:67540)
    at a.<anonymous> (https://beta.editor.paperize.io/editor.js:21:129355)
    at p (https://beta.editor.paperize.io/editor.js:9:41915)
    at b (https://beta.editor.paperize.io/editor.js:9:42176)
    at g (https://beta.editor.paperize.io/editor.js:9:42073)
```

**Expected behavior**
Doesn't error.

**Additional context**
From Discord user `@buddha`, ping him for feedback or when fixed!

**Comment by rs-wilson** [comment]
Buddha here - unfortunately I got this error again, this time with a template active and the pdf renderer actively showing a card. Switching back and forth currently makes this error happen every time. I do not know what I did to get it into this state 😞 - just working with templates, working with images, switching tabs and views and otherwise regular use.

**Comment by rs-wilson** [comment]
I think I got it:
1) Have a templated card
2) Click the pencil next to "template" to edit the template
3) Switch to the PNG renderer (default is pdf)
4) Close the edit window
5) The preview is on PDF renderer - switch it to PNG: 💥 error
